# streamlit/secrets.toml
# ⚠️ لا تشاركه أو ترفعه على GitHub!

[firebase]
apiKey = "AIzaSyCatHf0NlizimLq-FfAPGq4UYvMCHpCgwE"
authDomain = "master-tems.firebaseapp.com"
projectId = "master-tems"
storageBucket = "master-tems.firebasestorage.app"
messagingSenderId = "825388086153"
appId = "1:825388086153:web:2bfef6d4c99b4f3f82a758"
databaseURL = "https://master-tems-default-rtdb.firebaseio.com/"

[admin]
password = "Osama2b0a1h3i"